get Parachain balances, refactor getBalance and getDecimals
moonbeam-foundation/xcm-sdk pull request #217
Opened 2024-03-14 14:38 UTC by Rihyx

### Description

Please explain the changes this PR addresses here.

### Checklist

- [ ] If this requires a documentation change, I have created a PR in [moonbeam-docs](https://github.com/moonbeam-foundation/moonbeam-docs) repository.
- [ ] If this requires it, I have updated the Readme
- [ ] If necessary, I have updated the examples
- [ ] I have verified if I need to create/update unit tests
- [ ] I have verified if I need to create/update acceptance tests
- [ ] If necessary, I have run acceptance tests on this branch in CI

2024-03-20 10:15 UTC, mmaurello requested changes

2024-03-20 12:00 UTC, Rihyx commented on packages/config/src/configs/hydraDXAlphanet.ts
> +export const hydraDxAlphanetConfig = new ChainConfig({
Actually it is used here: https://github.com/moonbeam-foundation/xcm-sdk/pull/217/files#diff-04689b788dad65b6ce4b43e7344d3b854b1a95ad2c8692c6ece28ccd7d9a96b4R99
Not sure, maybe there is a better way to do it.
The idea was just to have assets which could be bridged.

2024-03-20 12:07 UTC, Rihyx commented on packages/config/src/chains.ts
> +  nativeCurrency: {
Change to use assets from [the assets file](https://github.com/moonbeam-foundation/xcm-sdk/blob/main/packages/config/src/assets.ts)

2024-03-20 12:09 UTC, Rihyx commented on packages/config/src/chains.ts
> +  nativeCurrency: {
I would avoid for now api calls in the config. I don't like the hardcoded values. But for now I would keep it simple

2024-04-14 23:00 UTC, mmaurello submitted a review, later dismissed

2024-04-15 22:11 UTC, mmaurello submitted a review, later dismissed

2024-04-16 07:43 UTC, mmaurello approved these changes

2024-04-16 07:45 UTC, merged